-- ==============================================================================
-- WMS CHOCOCHIPS SMART SYSTEM - SUPABASE POSTGRESQL COMPLETE DDL SCHEMA
-- ==============================================================================
-- File ini berisi seluruh definisi tabel, index, view stok, RLS policy,
-- dan publikasi realtime yang dibutuhkan oleh aplikasi WMS.
-- Aman dieksekusi berulang kali di Supabase SQL Editor.
-- ==============================================================================

-- 1. TABEL MASTER USERS & ROLE AKSES
CREATE TABLE IF NOT EXISTS public.wms_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  name TEXT,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'Operator',
  permissions JSONB DEFAULT '{}'::jsonb,
  nik VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO public.wms_users (username, password, role)
VALUES ('admin', 'admin123', 'All'),
       ('operator', '123456', 'Operator')
ON CONFLICT (username) DO NOTHING;

-- 2. TABEL MASTER PRODUK
CREATE TABLE IF NOT EXISTS public.master_produk (
  sku TEXT PRIMARY KEY,
  nama_produk TEXT NOT NULL,
  kategori TEXT DEFAULT 'Apparel',
  size TEXT DEFAULT 'Default',
  price NUMERIC DEFAULT 0,
  dealpos_channels JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. TABEL LOG PRODUK (MUTASI STOK & AUDIT TRAIL)
CREATE TABLE IF NOT EXISTS public.log_produk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  invoice TEXT NOT NULL,
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  area TEXT DEFAULT 'Warehouse',
  lokasi TEXT NOT NULL,
  qty NUMERIC DEFAULT 1,
  operator TEXT NOT NULL,
  keterangan TEXT DEFAULT '',
  raw_payload JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. TABEL STOCK OPNAME & ADJUSTMENT QUEUE
CREATE TABLE IF NOT EXISTS public.stock_opname_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sesi_id TEXT NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  lokasi TEXT NOT NULL,
  area TEXT DEFAULT 'Warehouse',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'PENDING',
  jenis TEXT DEFAULT 'Opname',
  alasan TEXT DEFAULT '',
  operator TEXT NOT NULL,
  invoice TEXT NOT NULL,
  tanggal_approve TIMESTAMPTZ,
  approved_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. TABEL PENERIMAAN PRODUKSI & KEDATANGAN BARANG
CREATE TABLE IF NOT EXISTS public.penerimaan_produksi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal_penerimaan DATE NOT NULL DEFAULT CURRENT_DATE,
  kategori TEXT NOT NULL DEFAULT 'Lokal CMT',
  no_surat_jalan TEXT NOT NULL,
  kode_produksi TEXT NOT NULL,
  warna TEXT DEFAULT '',
  size TEXT DEFAULT 'Default',
  qty NUMERIC DEFAULT 1,
  foto_url TEXT DEFAULT '',
  keterangan TEXT DEFAULT '',
  operator TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. TABEL FULFILLMENT PICKING LIST (SURAT JALAN)
CREATE TABLE IF NOT EXISTS public.picking_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_sj TEXT NOT NULL,
  tanggal TEXT DEFAULT '',
  tujuan TEXT DEFAULT 'Marketplace',
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  qty_req NUMERIC DEFAULT 0,
  qty_picked NUMERIC DEFAULT 0,
  lokasi TEXT DEFAULT '-',
  status TEXT DEFAULT 'PENDING',
  picker_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. TABEL PEMINJAMAN SEMENTARA (SPS)
CREATE TABLE IF NOT EXISTS public.peminjaman (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_peminjaman TEXT NOT NULL,
  pic TEXT NOT NULL,
  keperluan TEXT NOT NULL,
  tanggal_pinjam DATE NOT NULL DEFAULT CURRENT_DATE,
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  qty NUMERIC DEFAULT 1,
  lokasi TEXT DEFAULT '-',
  status TEXT DEFAULT 'Dipinjam',
  operator TEXT NOT NULL,
  tanggal_kembali DATE,
  keterangan TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. TABEL PENGELOLAAN REJECT, CUCI, PERMAK & DEFECT
CREATE TABLE IF NOT EXISTS public.perbaikan_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no TEXT UNIQUE NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  qty NUMERIC DEFAULT 1,
  lokasi_asal TEXT DEFAULT 'Warehouse',
  lokasi_sekarang TEXT DEFAULT 'PERBAIKAN-01',
  is_already_in_repair BOOLEAN DEFAULT false,
  sumber_barang TEXT DEFAULT 'Gudang',
  kategori_rusak TEXT NOT NULL,
  detail_kerusakan TEXT DEFAULT '',
  foto_urls JSONB DEFAULT '[]'::jsonb,
  foto_sesudah JSONB DEFAULT '[]'::jsonb,
  tahap TEXT DEFAULT 'REJECT',
  status_pengerjaan TEXT DEFAULT 'PENDING',
  qc_pic TEXT,
  qc_tanggal TIMESTAMPTZ,
  qc_catatan TEXT DEFAULT '',
  petugas_reparasi TEXT,
  reparasi_mulai TIMESTAMPTZ,
  reparasi_selesai TIMESTAMPTZ,
  reparasi_catatan TEXT DEFAULT '',
  biaya_reparasi NUMERIC DEFAULT 0,
  acc_harga_defect NUMERIC DEFAULT 0,
  acc_harga_by TEXT,
  acc_harga_tanggal TIMESTAMPTZ,
  acc_harga_catatan TEXT DEFAULT '',
  operator_input TEXT NOT NULL,
  qc_report_no TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.perbaikan_tickets ADD COLUMN IF NOT EXISTS qc_report_no TEXT;

-- 9. TABEL LAPORAN QUALITY CONTROL (QC)
CREATE TABLE IF NOT EXISTS public.qc_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_no TEXT UNIQUE NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  tipe_identifikasi TEXT DEFAULT 'sku',
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  kode_produksi TEXT DEFAULT '',
  warna TEXT DEFAULT '',
  size TEXT DEFAULT '-',
  sumber_batch TEXT DEFAULT 'Penerimaan CMT',
  status TEXT NOT NULL DEFAULT 'OKE',
  qty_diperiksa NUMERIC DEFAULT 1,
  qty_oke NUMERIC DEFAULT 1,
  qty_reject NUMERIC DEFAULT 0,
  kategori_rusak TEXT DEFAULT '',
  detail_kerusakan TEXT DEFAULT '',
  lokasi_barang TEXT DEFAULT '',
  target_penanganan TEXT DEFAULT 'REJECT',
  foto_urls JSONB DEFAULT '[]'::jsonb,
  gdrive_link TEXT DEFAULT '',
  catatan TEXT DEFAULT '',
  pic_qc TEXT NOT NULL,
  perbaikan_ticket_no TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 10. TABEL ADDRESS BOOK (AUTO-FILL CETAK LABEL)
CREATE TABLE IF NOT EXISTS public.address_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nama_penerima TEXT NOT NULL,
  no_telp TEXT,
  alamat TEXT NOT NULL,
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_address_book_nama ON public.address_book(nama_penerima);

-- 11. TABEL MODUL SDM / HR & KARYAWAN
CREATE TABLE IF NOT EXISTS public.karyawan (
  nik VARCHAR(50) PRIMARY KEY,
  nama VARCHAR(150) NOT NULL,
  divisi VARCHAR(100) NOT NULL DEFAULT 'Warehouse',
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'user',
  gaji_pokok NUMERIC(15, 2) NOT NULL DEFAULT 0,
  tunjangan NUMERIC(15, 2) NOT NULL DEFAULT 0,
  rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
  saldo_kasbon NUMERIC(15, 2) NOT NULL DEFAULT 0,
  email VARCHAR(150),
  no_hp VARCHAR(50),
  tgl_lahir DATE,
  tgl_bergabung DATE,
  alamat TEXT,
  hobi VARCHAR(255),
  kontak_darurat VARCHAR(255),
  foto TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.master_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_shift VARCHAR(50) NOT NULL UNIQUE,
  jam_masuk TIME NOT NULL,
  jam_pulang TIME NOT NULL,
  toleransi INTEGER NOT NULL DEFAULT 15,
  status VARCHAR(30) NOT NULL DEFAULT 'Aktif',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.roster_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  tanggal DATE NOT NULL,
  shift VARCHAR(50) NOT NULL,
  jam_masuk VARCHAR(10),
  jam_pulang VARCHAR(10),
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(nik, tanggal)
);

CREATE TABLE IF NOT EXISTS public.presensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  tanggal DATE NOT NULL,
  shift VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Hadir',
  jam_masuk TIME,
  jam_pulang TIME,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(nik, tanggal)
);

CREATE TABLE IF NOT EXISTS public.lembur (
  id VARCHAR(50) PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  nama VARCHAR(150) NOT NULL,
  divisi VARCHAR(100),
  tanggal DATE NOT NULL,
  deskripsi TEXT NOT NULL,
  jam_mulai TIME NOT NULL,
  jam_selesai TIME NOT NULL,
  durasi_jam NUMERIC(6, 2) NOT NULL DEFAULT 0,
  rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
  total_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
  approved_by VARCHAR(100),
  approved_at TIMESTAMPTZ,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.perijinan_cuti (
  id VARCHAR(50) PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  nama VARCHAR(150) NOT NULL,
  divisi VARCHAR(100),
  jenis VARCHAR(50) NOT NULL DEFAULT 'Cuti Tahunan',
  tgl_mulai DATE NOT NULL,
  tgl_selesai DATE NOT NULL,
  jumlah_hari INTEGER NOT NULL DEFAULT 1,
  alasan TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
  approved_by VARCHAR(100),
  approved_at TIMESTAMPTZ,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. VIEW REALTIME STOK OTOMATIS (SISA STOK = IN - OUT)
CREATE OR REPLACE VIEW public.view_stok_realtime AS
SELECT 
  lp.sku,
  lp.lokasi,
  lp.area,
  lp.nama_produk,
  lp.size,
  SUM(
    CASE 
      WHEN lp.type IN ('IN', 'ADJ_IN') THEN lp.qty
      WHEN lp.type IN ('OUT', 'ADJ_OUT') THEN -lp.qty
      ELSE 0
    END
  ) as sisa_stok,
  MAX(lp.created_at) as updated_at
FROM public.log_produk lp
GROUP BY lp.sku, lp.lokasi, lp.area, lp.nama_produk, lp.size;

-- 12. INDEKS PENCARIAN & PERFORMA CEPAT
CREATE INDEX IF NOT EXISTS idx_log_produk_sku ON public.log_produk(sku);
CREATE INDEX IF NOT EXISTS idx_log_produk_lokasi ON public.log_produk(lokasi);
CREATE INDEX IF NOT EXISTS idx_log_produk_created_at ON public.log_produk(created_at);
CREATE INDEX IF NOT EXISTS idx_log_produk_invoice ON public.log_produk(invoice);
CREATE INDEX IF NOT EXISTS idx_master_produk_nama ON public.master_produk(nama_produk);
CREATE INDEX IF NOT EXISTS idx_peminjaman_no ON public.peminjaman(no_peminjaman);
CREATE INDEX IF NOT EXISTS idx_peminjaman_sku ON public.peminjaman(sku);
CREATE INDEX IF NOT EXISTS idx_picking_list_no_sj ON public.picking_list(no_sj);
CREATE INDEX IF NOT EXISTS idx_stock_opname_sku ON public.stock_opname_queue(sku);
CREATE INDEX IF NOT EXISTS idx_perbaikan_ticket_no ON public.perbaikan_tickets(ticket_no);
CREATE INDEX IF NOT EXISTS idx_perbaikan_sku ON public.perbaikan_tickets(sku);
CREATE INDEX IF NOT EXISTS idx_perbaikan_tahap ON public.perbaikan_tickets(tahap);
CREATE INDEX IF NOT EXISTS idx_perbaikan_qc_report ON public.perbaikan_tickets(qc_report_no);
CREATE INDEX IF NOT EXISTS idx_qc_report_no ON public.qc_reports(report_no);
CREATE INDEX IF NOT EXISTS idx_qc_sku ON public.qc_reports(sku);
CREATE INDEX IF NOT EXISTS idx_qc_status ON public.qc_reports(status);
CREATE INDEX IF NOT EXISTS idx_qc_tanggal ON public.qc_reports(tanggal);
CREATE INDEX IF NOT EXISTS idx_roster_nik_tanggal ON public.roster_shift(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_presensi_nik_tanggal ON public.presensi(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_lembur_nik ON public.lembur(nik);
CREATE INDEX IF NOT EXISTS idx_cuti_nik ON public.perijinan_cuti(nik);

-- 13. ENABLE ROW LEVEL SECURITY & POLICY AKSES
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'wms_users', 'master_produk', 'log_produk', 'stock_opname_queue',
    'penerimaan_produksi', 'picking_list', 'peminjaman', 'perbaikan_tickets',
    'qc_reports', 'karyawan', 'master_shift', 'roster_shift', 'presensi',
    'lembur', 'perijinan_cuti', 'address_book'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Allow public all access" ON public.%I;', tbl);
    EXECUTE format('CREATE POLICY "Allow public all access" ON public.%I FOR ALL USING (true) WITH CHECK (true);', tbl);
  END LOOP;
END $$;

-- 14. AKTIFKAN REALTIME PUBLICATION UNTUK SEMUA TABEL UTAMA
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'log_produk', 'stock_opname_queue', 'peminjaman', 'picking_list',
    'perbaikan_tickets', 'qc_reports', 'karyawan', 'presensi', 'lembur'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables 
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = tbl
    ) THEN
      BEGIN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I;', tbl);
      EXCEPTION WHEN OTHERS THEN NULL;
      END;
    END IF;
  END LOOP;
END $$;
