-- ==============================================================================
-- WMS HR & EMPLOYEE MANAGEMENT SCHEMA (MODUL KARYAWAN & PRESENSI)
-- Untuk Project Baru: vxongwtxmhjixhzeoidp
-- ==============================================================================

-- 1. TABEL KARYAWAN
CREATE TABLE IF NOT EXISTS karyawan (
    nik VARCHAR(50) PRIMARY KEY,
    nama VARCHAR(150) NOT NULL,
    divisi VARCHAR(100) NOT NULL DEFAULT 'Warehouse',
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'user', -- 'admin' atau 'user'
    gaji_pokok NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunjangan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
    saldo_kasbon NUMERIC(15, 2) NOT NULL DEFAULT 0,
    email VARCHAR(150),
    no_hp VARCHAR(50),
    tgl_lahir DATE,
    tgl_bergabung DATE,
    alamat TEXT,
    hobi VARCHAR(255),
    kontak_darurat VARCHAR(255),
    foto TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tambahkan link NIK ke tabel wms_users yang sudah ada
ALTER TABLE wms_users ADD COLUMN IF NOT EXISTS nik VARCHAR(50);

-- 2. TABEL MASTER SHIFT
CREATE TABLE IF NOT EXISTS master_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_shift VARCHAR(50) NOT NULL UNIQUE,
    jam_masuk TIME NOT NULL,
    jam_pulang TIME NOT NULL,
    toleransi INTEGER NOT NULL DEFAULT 15,
    status VARCHAR(30) NOT NULL DEFAULT 'Aktif',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL ROSTER SHIFT HARIAN
CREATE TABLE IF NOT EXISTS roster_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(50) REFERENCES karyawan(nik) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    shift VARCHAR(50) NOT NULL,
    jam_masuk VARCHAR(10),
    jam_pulang VARCHAR(10),
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(nik, tanggal)
);

-- 4. TABEL PRESENSI & ABSENSI HARIAN
CREATE TABLE IF NOT EXISTS presensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(50) REFERENCES karyawan(nik) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    shift VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Hadir', -- 'Hadir', 'Terlambat', 'Ijin', 'Sakit', 'Alpha'
    jam_masuk TIME,
    jam_pulang TIME,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(nik, tanggal)
);

-- 5. TABEL PENGAJUAN LEMBUR
CREATE TABLE IF NOT EXISTS lembur (
    id VARCHAR(50) PRIMARY KEY,
    nik VARCHAR(50) REFERENCES karyawan(nik) ON DELETE CASCADE,
    nama VARCHAR(150) NOT NULL,
    divisi VARCHAR(100),
    tanggal DATE NOT NULL,
    deskripsi TEXT NOT NULL,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    durasi_jam NUMERIC(6, 2) NOT NULL DEFAULT 0,
    rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'Diajukan', -- 'Diajukan', 'Disetujui', 'Ditolak'
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABEL PERIJINAN & CUTI
CREATE TABLE IF NOT EXISTS perijinan_cuti (
    id VARCHAR(50) PRIMARY KEY,
    nik VARCHAR(50) REFERENCES karyawan(nik) ON DELETE CASCADE,
    nama VARCHAR(150) NOT NULL,
    divisi VARCHAR(100),
    jenis VARCHAR(50) NOT NULL DEFAULT 'Cuti Tahunan', -- 'Cuti Tahunan', 'Sakit', 'Ijin'
    tgl_mulai DATE NOT NULL,
    tgl_selesai DATE NOT NULL,
    jumlah_hari INTEGER NOT NULL DEFAULT 1,
    alasan TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Diajukan', -- 'Diajukan', 'Disetujui', 'Ditolak'
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing untuk query cepat
CREATE INDEX IF NOT EXISTS idx_roster_nik_tanggal ON roster_shift(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_presensi_nik_tanggal ON presensi(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_lembur_nik ON lembur(nik);
CREATE INDEX IF NOT EXISTS idx_cuti_nik ON perijinan_cuti(nik);

-- Row Level Security (RLS) & Policies
ALTER TABLE karyawan ENABLE ROW LEVEL SECURITY;
ALTER TABLE master_shift ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster_shift ENABLE ROW LEVEL SECURITY;
ALTER TABLE presensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE lembur ENABLE ROW LEVEL SECURITY;
ALTER TABLE perijinan_cuti ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow all access to karyawan" ON karyawan;
    CREATE POLICY "Allow all access to karyawan" ON karyawan FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow all access to master_shift" ON master_shift;
    CREATE POLICY "Allow all access to master_shift" ON master_shift FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow all access to roster_shift" ON roster_shift;
    CREATE POLICY "Allow all access to roster_shift" ON roster_shift FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow all access to presensi" ON presensi;
    CREATE POLICY "Allow all access to presensi" ON presensi FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow all access to lembur" ON lembur;
    CREATE POLICY "Allow all access to lembur" ON lembur FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow all access to perijinan_cuti" ON perijinan_cuti;
    CREATE POLICY "Allow all access to perijinan_cuti" ON perijinan_cuti FOR ALL USING (true) WITH CHECK (true);
END $$;

-- Realtime Publication
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE karyawan, master_shift, roster_shift, presensi, lembur, perijinan_cuti;
    EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
END $$;
