-- TABEL RIWAYAT AUDIT & HITUNG ULANG FISIK PENERIMAAN PRODUKSI
CREATE TABLE IF NOT EXISTS public.penerimaan_recount_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal_audit DATE NOT NULL DEFAULT CURRENT_DATE,
  auditor TEXT NOT NULL DEFAULT 'Auditor Fisik',
  kode_produksi TEXT NOT NULL,
  total_sebelumnya NUMERIC DEFAULT 0,
  total_fisik NUMERIC DEFAULT 0,
  total_selisih NUMERIC DEFAULT 0,
  general_notes TEXT DEFAULT '',
  details JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.penerimaan_recount_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access on recount logs" ON public.penerimaan_recount_logs FOR ALL USING (true);
