-- ============================================================
-- WMS CHOCOCHIPS SMART SYSTEM - SUPABASE DATABASE DDL SCHEMA
-- ============================================================

-- 1. TABEL MASTER USERS & ROLE AKSES
CREATE TABLE IF NOT EXISTS public.wms_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  name TEXT,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'Operator', -- 'All', 'Produk', 'Fulfillment', 'Peminjaman', 'Operator'
  permissions JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert Default Super Admin User jika belum ada
INSERT INTO public.wms_users (username, password, role)
VALUES ('admin', 'admin123', 'All'),
       ('operator', '123456', 'Operator')
ON CONFLICT (username) DO NOTHING;

-- 2. TABEL MASTER PRODUK
CREATE TABLE IF NOT EXISTS public.master_produk (
  sku TEXT PRIMARY KEY,
  nama_produk TEXT NOT NULL,
  kategori TEXT DEFAULT 'Apparel',
  size TEXT DEFAULT 'Default',
  price NUMERIC DEFAULT 0,
  dealpos_channels JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. TABEL LOG PRODUK (IN / OUT / ADJ_IN / ADJ_OUT)
CREATE TABLE IF NOT EXISTS public.log_produk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL, -- 'IN', 'OUT', 'ADJ_IN', 'ADJ_OUT'
  invoice TEXT NOT NULL,
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  area TEXT DEFAULT 'Warehouse',
  lokasi TEXT NOT NULL,
  qty NUMERIC DEFAULT 1,
  operator TEXT NOT NULL,
  keterangan TEXT DEFAULT '',
  raw_payload JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. TABEL STOCK OPNAME & ADJUSTMENT QUEUE
CREATE TABLE IF NOT EXISTS public.stock_opname_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sesi_id TEXT NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  lokasi TEXT NOT NULL,
  area TEXT DEFAULT 'Warehouse',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'PENDING', -- 'PENDING', 'APPROVED', 'REJECTED'
  jenis TEXT DEFAULT 'Opname', -- 'Opname', 'Manual'
  alasan TEXT DEFAULT '',
  operator TEXT NOT NULL,
  invoice TEXT NOT NULL,
  tanggal_approve TIMESTAMPTZ,
  approved_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. TABEL PENERIMAAN PRODUKSI & KEDATANGAN BARANG
CREATE TABLE IF NOT EXISTS public.penerimaan_produksi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal_penerimaan DATE NOT NULL DEFAULT CURRENT_DATE,
  kategori TEXT NOT NULL DEFAULT 'Lokal CMT', -- 'Lokal CMT', 'Kargo'
  no_surat_jalan TEXT NOT NULL,
  kode_produksi TEXT NOT NULL,
  warna TEXT DEFAULT '',
  size TEXT DEFAULT 'Default',
  qty NUMERIC DEFAULT 1,
  foto_url TEXT DEFAULT '',
  keterangan TEXT DEFAULT '',
  operator TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. TABEL FULFILLMENT PICKING LIST
CREATE TABLE IF NOT EXISTS public.picking_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_sj TEXT NOT NULL,
  tanggal TEXT DEFAULT '',
  tujuan TEXT DEFAULT 'Marketplace',
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  qty_req NUMERIC DEFAULT 0,
  qty_picked NUMERIC DEFAULT 0,
  lokasi TEXT DEFAULT '-',
  status TEXT DEFAULT 'PENDING', -- 'PENDING', 'TERCETAK', 'SELESAI'
  picker_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. TABEL PEMINJAMAN SEMENTARA (SPS)
CREATE TABLE IF NOT EXISTS public.peminjaman (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_peminjaman TEXT NOT NULL,
  pic TEXT NOT NULL,
  keperluan TEXT NOT NULL,
  tanggal_pinjam DATE NOT NULL DEFAULT CURRENT_DATE,
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  qty NUMERIC DEFAULT 1,
  lokasi TEXT DEFAULT '-',
  status TEXT DEFAULT 'Dipinjam', -- 'Dipinjam', 'Dikembalikan'
  operator TEXT NOT NULL,
  tanggal_kembali DATE,
  keterangan TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. VIEW REALTIME STOK OTOMATIS (SISA STOK = IN - OUT)
CREATE OR REPLACE VIEW public.view_stok_realtime AS
SELECT 
  lp.sku,
  lp.lokasi,
  lp.area,
  lp.nama_produk,
  lp.size,
  SUM(
    CASE 
      WHEN lp.type IN ('IN', 'ADJ_IN') THEN lp.qty
      WHEN lp.type IN ('OUT', 'ADJ_OUT') THEN -lp.qty
      ELSE 0
    END
  ) as sisa_stok,
  MAX(lp.created_at) as updated_at
FROM public.log_produk lp
GROUP BY lp.sku, lp.lokasi, lp.area, lp.nama_produk, lp.size;

-- 9. INDEXES UNTUK OPTIMASI PERFORMA TINGGI
CREATE INDEX IF NOT EXISTS idx_log_produk_sku ON public.log_produk(sku);
CREATE INDEX IF NOT EXISTS idx_log_produk_lokasi ON public.log_produk(lokasi);
CREATE INDEX IF NOT EXISTS idx_log_produk_created_at ON public.log_produk(created_at);
CREATE INDEX IF NOT EXISTS idx_log_produk_invoice ON public.log_produk(invoice);
CREATE INDEX IF NOT EXISTS idx_master_produk_nama ON public.master_produk(nama_produk);
CREATE INDEX IF NOT EXISTS idx_peminjaman_no ON public.peminjaman(no_peminjaman);
CREATE INDEX IF NOT EXISTS idx_peminjaman_sku ON public.peminjaman(sku);
CREATE INDEX IF NOT EXISTS idx_picking_list_no_sj ON public.picking_list(no_sj);
CREATE INDEX IF NOT EXISTS idx_stock_opname_sku ON public.stock_opname_queue(sku);

-- 10. ROW LEVEL SECURITY (RLS) & PUBLIC ANON ACCESS
ALTER TABLE public.wms_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_produk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.log_produk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_opname_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penerimaan_produksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.picking_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peminjaman ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all access" ON public.wms_users FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.master_produk FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.log_produk FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.stock_opname_queue FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.penerimaan_produksi FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.picking_list FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.peminjaman FOR ALL USING (true);

-- 11. ENABLE REALTIME PUBLICATION
ALTER PUBLICATION supabase_realtime ADD TABLE public.log_produk;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_opname_queue;
ALTER PUBLICATION supabase_realtime ADD TABLE public.peminjaman;
ALTER PUBLICATION supabase_realtime ADD TABLE public.picking_list;

-- ==============================================================================
-- MODUL HR & EMPLOYEE MANAGEMENT (DARI REPO WarehouseEmpl)
-- ==============================================================================

-- 12. TABEL KARYAWAN
CREATE TABLE IF NOT EXISTS public.karyawan (
    nik VARCHAR(50) PRIMARY KEY,
    nama VARCHAR(150) NOT NULL,
    divisi VARCHAR(100) NOT NULL DEFAULT 'Warehouse',
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'user',
    gaji_pokok NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunjangan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
    saldo_kasbon NUMERIC(15, 2) NOT NULL DEFAULT 0,
    email VARCHAR(150),
    no_hp VARCHAR(50),
    tgl_lahir DATE,
    tgl_bergabung DATE,
    alamat TEXT,
    hobi VARCHAR(255),
    kontak_darurat VARCHAR(255),
    foto TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tambahkan link NIK ke tabel wms_users
ALTER TABLE public.wms_users ADD COLUMN IF NOT EXISTS nik VARCHAR(50);

-- 13. TABEL MASTER SHIFT
CREATE TABLE IF NOT EXISTS public.master_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_shift VARCHAR(50) NOT NULL UNIQUE,
    jam_masuk TIME NOT NULL,
    jam_pulang TIME NOT NULL,
    toleransi INTEGER NOT NULL DEFAULT 15,
    status VARCHAR(30) NOT NULL DEFAULT 'Aktif',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. TABEL ROSTER SHIFT HARIAN
CREATE TABLE IF NOT EXISTS public.roster_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    shift VARCHAR(50) NOT NULL,
    jam_masuk VARCHAR(10),
    jam_pulang VARCHAR(10),
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(nik, tanggal)
);

-- 15. TABEL PRESENSI & ABSENSI HARIAN
CREATE TABLE IF NOT EXISTS public.presensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    shift VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Hadir',
    jam_masuk TIME,
    jam_pulang TIME,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(nik, tanggal)
);

-- 16. TABEL PENGAJUAN LEMBUR
CREATE TABLE IF NOT EXISTS public.lembur (
    id VARCHAR(50) PRIMARY KEY,
    nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
    nama VARCHAR(150) NOT NULL,
    divisi VARCHAR(100),
    tanggal DATE NOT NULL,
    deskripsi TEXT NOT NULL,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    durasi_jam NUMERIC(6, 2) NOT NULL DEFAULT 0,
    rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. TABEL PERIJINAN & CUTI
CREATE TABLE IF NOT EXISTS public.perijinan_cuti (
    id VARCHAR(50) PRIMARY KEY,
    nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
    nama VARCHAR(150) NOT NULL,
    divisi VARCHAR(100),
    jenis VARCHAR(50) NOT NULL DEFAULT 'Cuti Tahunan',
    tgl_mulai DATE NOT NULL,
    tgl_selesai DATE NOT NULL,
    jumlah_hari INTEGER NOT NULL DEFAULT 1,
    alasan TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes HR
CREATE INDEX IF NOT EXISTS idx_roster_nik_tanggal ON public.roster_shift(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_presensi_nik_tanggal ON public.presensi(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_lembur_nik ON public.lembur(nik);
CREATE INDEX IF NOT EXISTS idx_cuti_nik ON public.perijinan_cuti(nik);

-- RLS Policies HR
ALTER TABLE public.karyawan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_shift ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roster_shift ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lembur ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perijinan_cuti ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all access" ON public.karyawan FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.master_shift FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.roster_shift FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.presensi FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.lembur FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON public.perijinan_cuti FOR ALL USING (true);

-- Realtime HR
ALTER PUBLICATION supabase_realtime ADD TABLE public.karyawan;
ALTER PUBLICATION supabase_realtime ADD TABLE public.master_shift;
ALTER PUBLICATION supabase_realtime ADD TABLE public.roster_shift;
ALTER PUBLICATION supabase_realtime ADD TABLE public.presensi;
ALTER PUBLICATION supabase_realtime ADD TABLE public.lembur;
ALTER PUBLICATION supabase_realtime ADD TABLE public.perijinan_cuti;

