-- ==============================================================================
-- WMS CHOCOCHIPS SMART SYSTEM - COMPLETE MASTER DDL SCHEMA
-- ==============================================================================
-- Gunakan file ini untuk inisialisasi akun / project Supabase baru.
-- Jalankan seluruh skrip ini di SQL Editor Supabase baru Anda (1-Click Run).
-- Aman dijalankan berulang kali (Idempotent: IF NOT EXISTS).
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. TABEL MASTER USERS & ROLE AKSES
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wms_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  name TEXT,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'Operator',
  permissions JSONB DEFAULT '{}'::jsonb,
  nik VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Seed user default awal (bisa login langsung)
INSERT INTO public.wms_users (username, name, password, role)
VALUES ('admin', 'Super Administrator', 'admin123', 'Superadmin'),
       ('operator', 'Petugas Gudang', '123456', 'Operator')
ON CONFLICT (username) DO NOTHING;

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. TABEL MASTER PRODUK
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.master_produk (
  sku TEXT PRIMARY KEY,
  nama_produk TEXT NOT NULL,
  kategori TEXT DEFAULT 'Apparel',
  size TEXT DEFAULT 'Default',
  price NUMERIC DEFAULT 0,
  dealpos_channels JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. TABEL LOG PRODUK (MUTASI STOK & AUDIT TRAIL)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.log_produk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  invoice TEXT NOT NULL,
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  area TEXT DEFAULT 'Warehouse',
  lokasi TEXT NOT NULL,
  qty NUMERIC DEFAULT 1,
  operator TEXT NOT NULL,
  keterangan TEXT DEFAULT '',
  raw_payload JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. TABEL STOCK OPNAME & ADJUSTMENT QUEUE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.stock_opname_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sesi_id TEXT NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  lokasi TEXT NOT NULL,
  area TEXT DEFAULT 'Warehouse',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'PENDING',
  jenis TEXT DEFAULT 'Opname',
  alasan TEXT DEFAULT '',
  operator TEXT NOT NULL,
  invoice TEXT NOT NULL,
  tanggal_approve TIMESTAMPTZ,
  approved_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. TABEL PENERIMAAN PRODUKSI & KEDATANGAN BARANG
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.penerimaan_produksi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal_penerimaan DATE NOT NULL DEFAULT CURRENT_DATE,
  kategori TEXT NOT NULL DEFAULT 'Lokal CMT',
  no_surat_jalan TEXT NOT NULL,
  kode_produksi TEXT NOT NULL,
  warna TEXT DEFAULT '',
  size TEXT DEFAULT 'Default',
  qty NUMERIC DEFAULT 1,
  foto_url TEXT DEFAULT '',
  keterangan TEXT DEFAULT '',
  operator TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 6. TABEL FULFILLMENT PICKING LIST (SURAT JALAN)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.picking_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_sj TEXT NOT NULL,
  tanggal TEXT DEFAULT '',
  tujuan TEXT DEFAULT 'Marketplace',
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  qty_req NUMERIC DEFAULT 0,
  qty_picked NUMERIC DEFAULT 0,
  lokasi TEXT DEFAULT '-',
  status TEXT DEFAULT 'PENDING',
  picker_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 7. TABEL PEMINJAMAN SEMENTARA (SPS)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.peminjaman (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_peminjaman TEXT NOT NULL,
  pic TEXT NOT NULL,
  keperluan TEXT NOT NULL,
  tanggal_pinjam DATE NOT NULL DEFAULT CURRENT_DATE,
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  qty NUMERIC DEFAULT 1,
  lokasi TEXT DEFAULT '-',
  status TEXT DEFAULT 'Dipinjam',
  operator TEXT NOT NULL,
  tanggal_kembali DATE,
  keterangan TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 8. TABEL PENGELOLAAN REJECT, CUCI, PERMAK & DEFECT
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.perbaikan_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no TEXT UNIQUE NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  size TEXT DEFAULT '-',
  qty NUMERIC DEFAULT 1,
  lokasi_asal TEXT DEFAULT 'Warehouse',
  lokasi_sekarang TEXT DEFAULT 'PERBAIKAN-01',
  is_already_in_repair BOOLEAN DEFAULT false,
  sumber_barang TEXT DEFAULT 'Gudang',
  kategori_rusak TEXT NOT NULL,
  detail_kerusakan TEXT DEFAULT '',
  foto_urls JSONB DEFAULT '[]'::jsonb,
  foto_sesudah JSONB DEFAULT '[]'::jsonb,
  tahap TEXT DEFAULT 'REJECT',
  status_pengerjaan TEXT DEFAULT 'PENDING',
  qc_pic TEXT,
  qc_tanggal TIMESTAMPTZ,
  qc_catatan TEXT DEFAULT '',
  petugas_reparasi TEXT,
  reparasi_mulai TIMESTAMPTZ,
  reparasi_selesai TIMESTAMPTZ,
  reparasi_catatan TEXT DEFAULT '',
  biaya_reparasi NUMERIC DEFAULT 0,
  acc_harga_defect NUMERIC DEFAULT 0,
  acc_harga_by TEXT,
  acc_harga_tanggal TIMESTAMPTZ,
  acc_harga_catatan TEXT DEFAULT '',
  operator_input TEXT NOT NULL,
  qc_report_no TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 9. TABEL LAPORAN QUALITY CONTROL (QC)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.qc_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_no TEXT UNIQUE NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  tipe_identifikasi TEXT DEFAULT 'sku',
  sku TEXT NOT NULL,
  nama_produk TEXT NOT NULL,
  kode_produksi TEXT DEFAULT '',
  warna TEXT DEFAULT '',
  size TEXT DEFAULT '-',
  sumber_batch TEXT DEFAULT 'Penerimaan CMT',
  status TEXT NOT NULL DEFAULT 'OKE',
  qty_diperiksa NUMERIC DEFAULT 1,
  qty_oke NUMERIC DEFAULT 1,
  qty_reject NUMERIC DEFAULT 0,
  kategori_rusak TEXT DEFAULT '',
  detail_kerusakan TEXT DEFAULT '',
  lokasi_barang TEXT DEFAULT '',
  target_penanganan TEXT DEFAULT 'REJECT',
  foto_urls JSONB DEFAULT '[]'::jsonb,
  gdrive_link TEXT DEFAULT '',
  catatan TEXT DEFAULT '',
  pic_qc TEXT NOT NULL,
  perbaikan_ticket_no TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 10. TABEL MANUAL SHIPMENT (PENGIRIMAN MANUAL TOKO KE CUSTOMER)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.manual_shipment (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  no_pesanan TEXT UNIQUE NOT NULL,
  tanggal TIMESTAMPTZ DEFAULT now(),
  nama_pengirim TEXT NOT NULL DEFAULT 'CHOCOCHIPS',
  no_telp_store TEXT DEFAULT '',
  no_transaksi_pengirim TEXT[] DEFAULT '{}'::text[],
  nama_tujuan TEXT NOT NULL,
  no_telp_tujuan TEXT DEFAULT '',
  alamat_tujuan TEXT NOT NULL,
  notes_paket TEXT DEFAULT '',
  no_transaksi_customer TEXT DEFAULT '',
  jasa_kirim TEXT DEFAULT '',
  no_resi TEXT DEFAULT '',
  status TEXT DEFAULT 'diterima' CHECK (status IN ('diterima', 'diproses', 'dikirim', 'batal', 'DELETED')),
  submitted_by TEXT DEFAULT '',
  pic_store TEXT DEFAULT '',
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 11. TABEL PENGECEKAN SURAT JALAN (TARIKAN MD / PENERIMAAN OUTLET)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pengecekan_sj (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  no_sj TEXT NOT NULL,
  tanggal_sj DATE NOT NULL DEFAULT CURRENT_DATE,
  source TEXT NOT NULL DEFAULT 'Gudang Pusat',
  destination TEXT NOT NULL DEFAULT 'Outlet',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'selesai', 'DELETED')),
  status_komparasi TEXT DEFAULT 'COCOK' CHECK (status_komparasi IN ('COCOK', 'SELISIH')),
  total_qty_sj NUMERIC DEFAULT 0,
  total_qty_terima NUMERIC DEFAULT 0,
  total_sku INTEGER DEFAULT 0,
  submitted_by TEXT NOT NULL DEFAULT '',
  catatan TEXT DEFAULT '',
  items JSONB DEFAULT '[]'::jsonb,
  items_json TEXT DEFAULT '',
  sync_status TEXT DEFAULT 'synced' CHECK (sync_status IN ('synced', 'pending_sync')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 12. TABEL ADDRESS BOOK (AUTO-FILL ALAMAT CETAK LABEL)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.address_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nama_penerima TEXT NOT NULL,
  no_telp TEXT,
  alamat TEXT NOT NULL,
  keterangan TEXT,
  jasa_kirim TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 13. TABEL MODUL SDM / HR & KARYAWAN
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.karyawan (
  nik VARCHAR(50) PRIMARY KEY,
  nama VARCHAR(150) NOT NULL,
  divisi VARCHAR(100) NOT NULL DEFAULT 'Warehouse',
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'user',
  gaji_pokok NUMERIC(15, 2) NOT NULL DEFAULT 0,
  tunjangan NUMERIC(15, 2) NOT NULL DEFAULT 0,
  rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
  saldo_kasbon NUMERIC(15, 2) NOT NULL DEFAULT 0,
  email VARCHAR(150),
  no_hp VARCHAR(50),
  tgl_lahir DATE,
  tgl_bergabung DATE,
  alamat TEXT,
  hobi VARCHAR(255),
  kontak_darurat VARCHAR(255),
  foto TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.master_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_shift VARCHAR(50) NOT NULL UNIQUE,
  jam_masuk TIME NOT NULL,
  jam_pulang TIME NOT NULL,
  toleransi INTEGER NOT NULL DEFAULT 15,
  status VARCHAR(30) NOT NULL DEFAULT 'Aktif',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.roster_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  tanggal DATE NOT NULL,
  shift VARCHAR(50) NOT NULL,
  jam_masuk VARCHAR(10),
  jam_pulang VARCHAR(10),
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(nik, tanggal)
);

CREATE TABLE IF NOT EXISTS public.presensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  tanggal DATE NOT NULL,
  shift VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Hadir',
  jam_masuk TIME,
  jam_pulang TIME,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(nik, tanggal)
);

CREATE TABLE IF NOT EXISTS public.lembur (
  id VARCHAR(50) PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  nama VARCHAR(150) NOT NULL,
  divisi VARCHAR(100),
  tanggal DATE NOT NULL,
  deskripsi TEXT NOT NULL,
  jam_mulai TIME NOT NULL,
  jam_selesai TIME NOT NULL,
  durasi_jam NUMERIC(6, 2) NOT NULL DEFAULT 0,
  rate_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
  total_lembur NUMERIC(15, 2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
  approved_by VARCHAR(100),
  approved_at TIMESTAMPTZ,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.perijinan_cuti (
  id VARCHAR(50) PRIMARY KEY,
  nik VARCHAR(50) REFERENCES public.karyawan(nik) ON DELETE CASCADE,
  nama VARCHAR(150) NOT NULL,
  divisi VARCHAR(100),
  jenis VARCHAR(50) NOT NULL DEFAULT 'Cuti Tahunan',
  tgl_mulai DATE NOT NULL,
  tgl_selesai DATE NOT NULL,
  jumlah_hari INTEGER NOT NULL DEFAULT 1,
  alasan TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
  approved_by VARCHAR(100),
  approved_at TIMESTAMPTZ,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 14. TABEL PROYEK & AGENDA KERJA WMS
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wms_projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  status TEXT DEFAULT 'in_progress' 
    CHECK (status IN ('planned', 'in_progress', 'review', 'completed', 'on_hold')),
  priority TEXT DEFAULT 'medium' 
    CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  category TEXT DEFAULT 'Infrastruktur',
  pic TEXT DEFAULT '',
  start_date DATE,
  deadline DATE,
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  tasks JSONB DEFAULT '[]'::jsonb,
  attachments JSONB DEFAULT '[]'::jsonb,
  created_by TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.wms_agenda (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  start_date DATE NOT NULL,
  end_date DATE,
  is_all_day BOOLEAN DEFAULT false,
  start_time TEXT DEFAULT '',
  end_time TEXT DEFAULT '',
  category TEXT DEFAULT 'umum' 
    CHECK (category IN ('meeting', 'operasional', 'project', 'supplier', 'urgent', 'umum')),
  location TEXT DEFAULT '',
  pic TEXT DEFAULT '',
  project_id UUID REFERENCES public.wms_projects(id) ON DELETE SET NULL,
  attachments JSONB DEFAULT '[]'::jsonb,
  created_by TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 15. TABEL ROADMAP & REQUEST FITUR WMS (wms_roadmap)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wms_roadmap (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  status TEXT DEFAULT 'ideation' CHECK (status IN ('ideation', 'planned', 'in_progress', 'completed', 'canceled')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  type TEXT DEFAULT 'feature' CHECK (type IN ('feature', 'improvement', 'bugfix', 'infra')),
  created_by TEXT DEFAULT '',
  target_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 16. TABEL DOKUMENTASI SISTEM & SOP WMS (wms_system_docs)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wms_system_docs (
  section_id TEXT PRIMARY KEY,
  content TEXT NOT NULL DEFAULT '',
  updated_by TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 17. TABEL KONFIGURASI STORE & OUTLET (outlet_config)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.outlet_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nama TEXT NOT NULL,
  fulfillment TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 18. TABEL PENGATURAN GLOBAL WMS & INTEGRASI (wms_settings)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wms_settings (
  id BIGINT PRIMARY KEY,
  fonnte_token TEXT DEFAULT '',
  fonnte_group_target TEXT DEFAULT '',
  fonnte_auto_send BOOLEAN DEFAULT true,
  gas_endpoint TEXT DEFAULT '',
  manual_shipment_gas_url TEXT DEFAULT '',
  gdrive_gas_url TEXT DEFAULT '',
  gdrive_folder_url TEXT DEFAULT '',
  roles JSONB DEFAULT '{}'::jsonb,
  agenda_categories JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- 19. VIEWS OTOMATIS (STOK REAL FISIK & STOK REALTIME)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.stok_real_fisik AS
SELECT 
  lp.sku,
  lp.lokasi,
  lp.area,
  MAX(lp.nama_produk) as nama_produk,
  MAX(lp.size) as size,
  SUM(
    CASE 
      WHEN lp.type IN ('IN', 'ADJ_IN') THEN lp.qty
      WHEN lp.type IN ('OUT', 'ADJ_OUT') THEN -lp.qty
      ELSE 0
    END
  ) as sisa_stok,
  MAX(lp.created_at) as updated_at
FROM public.log_produk lp
GROUP BY lp.sku, lp.lokasi, lp.area;

CREATE OR REPLACE VIEW public.view_stok_realtime AS
SELECT 
  lp.sku,
  lp.lokasi,
  lp.area,
  lp.nama_produk,
  lp.size,
  SUM(
    CASE 
      WHEN lp.type IN ('IN', 'ADJ_IN') THEN lp.qty
      WHEN lp.type IN ('OUT', 'ADJ_OUT') THEN -lp.qty
      ELSE 0
    END
  ) as sisa_stok,
  MAX(lp.created_at) as updated_at
FROM public.log_produk lp
GROUP BY lp.sku, lp.lokasi, lp.area, lp.nama_produk, lp.size;

-- ──────────────────────────────────────────────────────────────────────────────
-- 20. INDEKS PENCARIAN & PERFORMA
-- ──────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_log_produk_sku ON public.log_produk(sku);
CREATE INDEX IF NOT EXISTS idx_log_produk_lokasi ON public.log_produk(lokasi);
CREATE INDEX IF NOT EXISTS idx_log_produk_created_at ON public.log_produk(created_at);
CREATE INDEX IF NOT EXISTS idx_log_produk_invoice ON public.log_produk(invoice);
CREATE INDEX IF NOT EXISTS idx_master_produk_nama ON public.master_produk(nama_produk);
CREATE INDEX IF NOT EXISTS idx_peminjaman_no ON public.peminjaman(no_peminjaman);
CREATE INDEX IF NOT EXISTS idx_peminjaman_sku ON public.peminjaman(sku);
CREATE INDEX IF NOT EXISTS idx_picking_list_no_sj ON public.picking_list(no_sj);
CREATE INDEX IF NOT EXISTS idx_stock_opname_sku ON public.stock_opname_queue(sku);
CREATE INDEX IF NOT EXISTS idx_perbaikan_ticket_no ON public.perbaikan_tickets(ticket_no);
CREATE INDEX IF NOT EXISTS idx_perbaikan_sku ON public.perbaikan_tickets(sku);
CREATE INDEX IF NOT EXISTS idx_qc_report_no ON public.qc_reports(report_no);
CREATE INDEX IF NOT EXISTS idx_qc_sku ON public.qc_reports(sku);
CREATE INDEX IF NOT EXISTS idx_manual_shipment_no ON public.manual_shipment(no_pesanan);
CREATE INDEX IF NOT EXISTS idx_pengecekan_sj_no ON public.pengecekan_sj(no_sj);
CREATE INDEX IF NOT EXISTS idx_address_book_nama ON public.address_book(nama_penerima);
CREATE INDEX IF NOT EXISTS idx_roster_nik_tanggal ON public.roster_shift(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_presensi_nik_tanggal ON public.presensi(nik, tanggal);
CREATE INDEX IF NOT EXISTS idx_lembur_nik ON public.lembur(nik);
CREATE INDEX IF NOT EXISTS idx_cuti_nik ON public.perijinan_cuti(nik);
CREATE INDEX IF NOT EXISTS idx_wms_projects_status ON public.wms_projects(status);
CREATE INDEX IF NOT EXISTS idx_wms_projects_deadline ON public.wms_projects(deadline);
CREATE INDEX IF NOT EXISTS idx_wms_agenda_start_date ON public.wms_agenda(start_date);
CREATE INDEX IF NOT EXISTS idx_wms_agenda_category ON public.wms_agenda(category);
CREATE INDEX IF NOT EXISTS idx_wms_agenda_project_id ON public.wms_agenda(project_id);
CREATE INDEX IF NOT EXISTS idx_wms_roadmap_status ON public.wms_roadmap(status);
CREATE INDEX IF NOT EXISTS idx_wms_roadmap_created_at ON public.wms_roadmap(created_at);
CREATE INDEX IF NOT EXISTS idx_outlet_config_nama ON public.outlet_config(nama);

-- ──────────────────────────────────────────────────────────────────────────────
-- 21. ROW LEVEL SECURITY (RLS) & ACCESS POLICIES
-- ──────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'wms_users', 'master_produk', 'log_produk', 'stock_opname_queue',
    'penerimaan_produksi', 'picking_list', 'peminjaman', 'perbaikan_tickets',
    'qc_reports', 'manual_shipment', 'pengecekan_sj', 'address_book',
    'karyawan', 'master_shift', 'roster_shift', 'presensi', 'lembur', 'perijinan_cuti',
    'wms_projects', 'wms_agenda', 'wms_roadmap', 'wms_system_docs', 'outlet_config', 'wms_settings'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Allow public all access" ON public.%I;', tbl);
    EXECUTE format('CREATE POLICY "Allow public all access" ON public.%I FOR ALL USING (true) WITH CHECK (true);', tbl);
  END LOOP;
END $$;

-- ──────────────────────────────────────────────────────────────────────────────
-- 22. AKTIFKAN REALTIME REPLICATION UNTUK TABEL UTAMA
-- ──────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'log_produk', 'stock_opname_queue', 'peminjaman', 'picking_list',
    'perbaikan_tickets', 'qc_reports', 'manual_shipment', 'pengecekan_sj',
    'karyawan', 'presensi', 'lembur', 'wms_projects', 'wms_agenda',
    'wms_roadmap', 'wms_system_docs', 'outlet_config', 'wms_settings'
  ];
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  FOREACH tbl IN ARRAY tables LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables 
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = tbl
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I;', tbl);
    END IF;
  END LOOP;
END $$;

-- ==============================================================================
-- SELESAI! Seluruh 24 tabel & skema database Supabase telah siap digunakan 100%.
-- ==============================================================================

